# Add latest environment
FROM nginx:latest

# Copy softy-pinko files to nginx
COPY ./softy-pinko-front-end-main /var/www/html/softy-pinko-front-end
COPY ./softy-pinko-front-end.conf  /etc/nginx/conf.d/default.conf
