services:
  proxy:
    build: ./proxy/
    image: softy-pinko-proxy:task5
    ports:
      - '80:80'

  back-end:
    build: ./back-end/
    image: softy-pinko-back-end:task5
    deploy:
      mode: replicated
      replicas: 2
    # ports:
    #   - '5252:5252'
    depends_on:
      - front-end

  front-end:
    build: ./front-end/
    image: softy-pinko-front-end:task5
    # ports:
    #   - '9000:9000'
